### PR TITLE
Ipu6 probe ordering fixes

### PR DESCRIPTION
**Pull request by jwrdegoede**
I have been working on making the ipu6-driver stack work on a Lenovo Thinkpad X1 Yoga gen 7 (alderlake) with a 6.0 kernel and using the INT3472 mainline kernel driver for power-control.

With the ipu6 code using acpi_dev_ready_for_enumeration() for kernel versions >= 5.17 ipu_psys_init() was returning -EPROBE_DEFER (and still does a number of time when letting udev automatically load the modules).

After fixing this I hit a bunch of other probe-ordering issues. This pull-req fixes all of these.

When combined with a matching pull-req for ivsc-drivers which I'm about to submit as well as [this](https://lore.kernel.org/linux-acpi/20221022150722.31787-1-hdegoede@redhat.com/) mainline kernel patch (+ the "standard" mainline patches) this results in a working camera on the Lenovo Thinkpad X1 Yoga gen 7 for me, with the modules autoloaded by udev and with the module load ordering not mattering.

Note before this patch-series there are a bunch of issues / NULL pointer dereferences when intel_ipu6_isys is already loaded by the time all the deps are ready (once we no longer get a -EPROBE_DEFER).

Cc: @mrhpearson, @vicamo , @cjechlitschek

### CODE REVIEW

**Comment by jwrdegoede** [comment]
Note I believe that (together with the ivsc-driver fixes) this pull-requests closes issues #48 and #55.

**Comment by hao-yao** [comment]
@jwrdegoede Thanks for you work. We have ported your patches and validated on Lenovo Thinkpad X1 Yoga device. Latest repo should contain your changes now.

**Comment by jwrdegoede** [comment]
> > @jwrdegoede Thanks for you work. We have ported your patches and validated on Lenovo Thinkpad X1 Yoga device. Latest repo should contain your changes now.
> 
> I just checked out the latest master branch and I'm not seeing my changes there?

Ok, so I see something resembling some of my changes in commit bf7c01236f77a61e3a041dd54c80fa3865c692f4 ("Oasis PV release on 2022-11-12")

But: they were rewritten and all squashed into one big commit, there are a number of issues with this:

1. The commit messages which explain what was not working before, why things did not work before and how the commit fixes things were all lost. This is important information to keep around and I do not like that I spend a lot of time writing proper commit messages only to have all this thrown away.
2. My authorship was lost which is not how one is supposed to deal with FOSS contributions, maintaining authorship of commits is important / common decency .
3. Only 2 of 6 patches where added in some rewritten form; and one of them introduced 2 bugs to the changes in the rewrite.
4. 4 of the patches, including some vital bugfixes where not merged at all.

I'll prepare a new pull-req fixing the 2 bugs introduced by rewriting my patches + the 4 missing patches and push that to the branch for this pull-req.

Next time of there are conflicting changes pending (were there?) please just push out your changes and then ask me to do a rebase. And then after the rebase do a clean merge of my patches, preserving the commit messages and author info.

**Comment by norbusan** [comment]
I can only agree to the full extend with @jwrdegoede : removing commit messages and not doing proper attribution, as well as botching the PR is not a good idea.

Thanks to Hans for picking up the pieces!

**Comment by hao-yao** [comment]
@jwrdegoede Sorry for that and I'll try to keep your commits on master branch. I'll fix the git tree.

**Comment by hao-yao** [comment]
@jwrdegoede I cherry-picked your changes to master branch and cleaned some commits. For commit [5a36712](https://github.com/intel/ipu6-drivers/pull/58/commits/5a36712499e83cdf1ec6b89e13df573e09ebe565) and [eb97475](https://github.com/intel/ipu6-drivers/pull/58/commits/eb97475ef5cf5288dc6162afc30443713514d8c3), we need review and test internally. Could you help to change this PR to only contain this 2 commits and do a rebase? So we can merge this PR once we validated it, before our next formal release.

**Comment by jwrdegoede** [comment]
> @jwrdegoede I cherry-picked your changes to master branch and cleaned some commits.

Thank you I'll take a look tomorrow.

On a side note I've also started writing a patch to fix compilation errors with 6.1-rc2 and higher (some linux-media changes landed in rc2 rather then in rc1). I'll submit the build fixes for this in a separate pull-req tomorrow (assuming I get things working).

**Comment by hao-yao** [comment]
> On a side note I've also started writing a patch to fix compilation errors with 6.1-rc2 and higher (some linux-media changes landed in rc2 rather then in rc1). I'll submit the build fixes for this in a separate pull-req tomorrow (assuming I get things working).

Thanks again. We couldn't validate on kernel 6.1 in time and I thought Vicamo's [commit 308c7cc1d6fe742a507cab5ba2818757e20f363f](https://github.com/intel/ipu6-drivers/commit/308c7cc1d6fe742a507cab5ba2818757e20f363f) fixed compilation issues.

**Comment by twouters** [comment]
> > On a side note I've also started writing a patch to fix compilation errors with 6.1-rc2 and higher (some linux-media changes landed in rc2 rather then in rc1). I'll submit the build fixes for this in a separate pull-req tomorrow (assuming I get things working).
> 
> Thanks again. We couldn't validate on kernel 6.1 in time and I thought Vicamo's [commit 308c7cc1d6fe742a507cab5ba2818757e20f363f](https://github.com/intel/ipu6-drivers/commit/308c7cc1d6fe742a507cab5ba2818757e20f363f) fixed compilation issues.

It fixed it for rc1, but builds fail for later RC release s as I reported here: https://github.com/intel/ipu6-drivers/issues/63

**Comment by jwrdegoede** [comment]
@hao-yao thanks for the fixed push, things look good now, much appreciated.

> For commit [5a36712](https://github.com/intel/ipu6-drivers/pull/58/commits/5a36712499e83cdf1ec6b89e13df573e09ebe565) and [eb97475](https://github.com/intel/ipu6-drivers/pull/58/commits/eb97475ef5cf5288dc6162afc30443713514d8c3), we need review and test internally.

Commit 5a36712499e83cdf1ec6b89e13df573e09ebe565 ("ipu6: ipu_pci_probe(): Fix crash on ipu_psys_init() failure ") is already fixed in another way by changes brought in through the  "Oasis PV release on 2022-11-12" change, specifically the `goto out_ipu_bus_del_devices:` path in `ipu_pci_probe()` was changed to replace `if (isp->psys)` checks with `if (!IS_ERR_OR_NULL(isp->psys))` checks and the same for `isp->isys` checks which fixes the crash in a different way.   If you look at commit 5a36712499e83cdf1ec6b89e13df573e09ebe565 I do believe my way of fixing this is a bit cleaner, but either way is fine.

Commit eb97475ef5cf5288dc6162afc30443713514d8c3 ("ipu6: ipu_pci_probe(): Fix "Runtime PM usage count underflow!" on probe errors") likewise was already fixed by changes brought in through the  "Oasis PV release on 2022-11-12" change, specifically these 2 lines:

```
	pm_runtime_put_noidle(&pdev->dev);
	pm_runtime_allow(&pdev->dev);
```

Have been moved a bit lower inside `ipu_pci_probe()` which is the same fix as I did in eb97475ef5cf5288dc6162afc30443713514d8c3.

Note compared to eb97475ef5cf5288dc6162afc30443713514d8c3 there still is a small remaining issue with a pm_runtime unbalance when `ipu_init_debugfs()` fails (which is unlikely, so not really a problem). I'll submit a fix for this in a separate pull-req, but I first I want to land some other more important fixes which will conflict if all landed at once, so I will do that pull-request later.

Since the issues from the 2 remaining commits are already fixed, I believe this pull-req can be closed now.

**Comment by jwrdegoede** [comment]
The 2 pull-reqs with important fixes which I mentioned are ready now:

1.  6.1 build fixes (non trivial) #67 
2.  Another probe-ordering fix #68

**Pull request closed without merging**
