### PR TITLE
media: i2c: skip hwcfg checking for Dell Non-CVF platforms

### PR DESCRIPTION
**Pull request by vicamo**
Closes: #235

### CODE REVIEW

**Comment by drhooray** [comment]
Thanks for the patch, vicamo.

Because there is a solution to fix the issue with the following changes:

[Ignore bad graph port nodes on Dell XPS 9315](https://lore.kernel.org/all/20240212100032.346422-3-sakari.ailus@linux.intel.com/T/#m42c88d6a511c348e239ea3c773dfe82551d68d02)
[ACPI: utils: Make acpi_handle_path() not static](https://lore.kernel.org/all/20240212100032.346422-2-sakari.ailus@linux.intel.com/T/#ma205e5b663292112e866f9ab5d5663cdfc34fe0b)
[ACPI: property: Ignore bad data nodes](https://lore.kernel.org/all/20240212100032.346422-2-sakari.ailus@linux.intel.com/T/#mc0b77df8f0d37e56440f0ba0f108f888575354d2)

Plus, to add Dell device into the list as below:
https://kernel.googlesource.com/pub/scm/linux/kernel/git/torvalds/linux.git/+/refs/tags/v6.9/drivers/acpi/mipi-disco-img.c#728

Is that ok for you?

btw, @hao-yao 

Since this PR has been validated on the vicamo's side. If we decide to use this solution, we will also need to run tests for it.

**Comment by vicamo** [comment]
> Thanks for the patch, vicamo.
> 
> Because there is a solution to fix the issue with the following changes:
> 
> [Ignore bad graph port nodes on Dell XPS 9315](https://lore.kernel.org/all/20240212100032.346422-3-sakari.ailus@linux.intel.com/T/#m42c88d6a511c348e239ea3c773dfe82551d68d02) [ACPI: utils: Make acpi_handle_path() not static](https://lore.kernel.org/all/20240212100032.346422-2-sakari.ailus@linux.intel.com/T/#ma205e5b663292112e866f9ab5d5663cdfc34fe0b) [ACPI: property: Ignore bad data nodes](https://lore.kernel.org/all/20240212100032.346422-2-sakari.ailus@linux.intel.com/T/#mc0b77df8f0d37e56440f0ba0f108f888575354d2)
> 
> Plus, to add Dell device into the list as below: https://kernel.googlesource.com/pub/scm/linux/kernel/git/torvalds/linux.git/+/refs/tags/v6.9/drivers/acpi/mipi-disco-img.c#728
> 
> Is that ok for you?
> 
> btw, @hao-yao
> 
> Since this PR has been validated on the vicamo's side. If we decide to use this solution, we will also need to run tests for it.

There are a few concerns. One, the fixes you mentioned are to be backported into kernel tree, and while we're running dkms across a few number of kernels, that means it will take multiple submits instead of just one. And while the hwcfg check is in the ipu6-drivers dkms, the affected kernels list may be even longer than officially planed ones. However, we always prefer upstreamed patches over sauced ones, that's something I don't have solid answer by this moment, at least not before verified on Dell 9315. You should commit at your best fit.

**Comment by jwrdegoede** [comment]
Note that this is also fixed by the combination of:

- https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/acpi?id=c7be64355fccfe7d4727681e32fce07113e40af1
- https://git.linuxtv.org/media_stage.git/commit/drivers/media/pci?id=440de616e76e225feb1182e2ca34cc0d6f00555c

Or when using the downstream cio2-bridge.c instead of the upstream ipu-bridge.c :
- https://github.com/intel/ipu6-drivers/pull/241

**Comment by jwrdegoede** [comment]
Also note that:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/acpi?id=c7be64355fccfe7d4727681e32fce07113e40af1

fixes this for all Dell models, not just the XPS 13 9515, e.g. the XPS 13 9520 and the Latitude 9420 are also affected by having incomplete device-properties for the sensors in their ACPI tables.

**Comment by vicamo** [comment]
> Note that this is also fixed by the combination of:
> 
> * https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/acpi?id=c7be64355fccfe7d4727681e32fce07113e40af1
> * https://git.linuxtv.org/media_stage.git/commit/drivers/media/pci?id=440de616e76e225feb1182e2ca34cc0d6f00555c
> 
> Or when using the downstream cio2-bridge.c instead of the upstream ipu-bridge.c :
> 
> * [cio2-bridge: Fill in link frequency for all sensors #241](https://github.com/intel/ipu6-drivers/pull/241)

Verified these on Dell Latitude 9420. Thank you.

While we need to keep 6.5 kernel running for a while, Ubuntu will still include this work-around for 6.5 builds. For 6.8 and on, the aforementioned fixes are used instead. I'm closing this with the assumption that people should also prefer upstreamed fixes.

**Pull request closed without merging**
