### PR TITLE
Fix compilation with kernel 6.1

### PR DESCRIPTION
**Pull request by jwrdegoede**
Fix compilation with kernel 6.1, deal with the media-controller changes which have landed in 6.1-rc2.

Closes: #63

Signed-off-by: Hans de Goede <hdegoede@redhat.com>

### CODE REVIEW

**Comment by twouters** [comment]
Tried again by building your branch and I hit the same issue

**Comment by twouters** [comment]
(fyi: 6.0.x boots fine with this)

**Comment by jwrdegoede** [comment]
Hmm, I have so far only tested this on a Lenovo ThinkPad X1 Yoga Gen 7

 I did need to either blacklist the intel-ipu6* modules in modprobe.conf and then load them manually starting with intel-ipu6, otherwise I would get a different NULL pointer deref. I have a fix for this in #68 now.

I do have  a Dell XPS 9360 here, which I expect is closer to your Dell then then ThinkPad Yoga. I will give that a try to, but I don't expect to get around that before next week Monday.

**Comment by jwrdegoede** [comment]
@mrhpearson, @vicamo Note if you want to build / try the IPU6 drivers with 6.1-rc2 or newer you will need this pull-req; and if you let udev load the modules at boot rather then doing it manually you will also need #68 to avoid a kernel crash due to a probe-ordering issue.

**Comment by vicamo** [comment]
> 

Yes, I am testing a new Ubuntu release with these combined.

**Comment by vicamo** [comment]
> > 
> 
> Yes, I am testing a new Ubuntu release with these combined.

I have boot hang with or without #68 on v6.1-rc6.

**Comment by vicamo** [comment]
> > > 
> > 
> > 
> > Yes, I am testing a new Ubuntu release with these combined.
> 
> I have boot hang with or without #68 on v6.1-rc6.

Turns out it's a problem in vsc, and can be fixed by https://github.com/intel/ivsc-driver/pull/27.

**Comment by twouters** [comment]
Can confirm that this change fixes compilation on v6.1-rc6 and v6.1-rc7 and mentioned fix for ivsc-driver fixes the boot hang

**Comment by hao-yao** [comment]
validated with #69

**Comment by jwrdegoede** [comment]
Note I have just added an extra patch fixing the ipu6-driver crashing with linux-next / with the upcoming 6.2-rc# kernels.

**Comment by jwrdegoede** [comment]
Ping? Is there a reason why this has not been merged yet?

**Comment by heregoesnoth** [comment]
Please! :sob:

**Pull request merged**
