### PR TITLE
cio2-bridge: Fix compilation with kernel >= 6.3

### PR DESCRIPTION
**Pull request by jwrdegoede**
Fix cio2-bridge compilation with kernel 6.3 and later.

### CODE REVIEW

**Comment by hao-yao** [comment]
Seems we can use software_node_register_node_group() directly instead of software_node_register_nodes() and no need to use kernel version macro. @jwrdegoede How do you think?

**Comment by hao-yao** [comment]
Hi @jwrdegoede , seems latest linux kernel have solved this issue at drivers/media/pci/intel/ipu3/cio2-bridge.c. I think we can directly copy that back.

**Comment by jwrdegoede** [comment]
> Seems we can use software_node_register_node_group() directly instead of software_node_register_nodes() and no need to use kernel version macro. @jwrdegoede How do you think?

> seems latest linux kernel have solved this issue at drivers/media/pci/intel/ipu3/cio2-bridge.c. I think we can directly copy that back.

If software_node_register_node_group()  is available in all the kernel versions you want to support then yes that should work.

Shall I push a new version cherry-picking the upstream fix + adding https://github.com/hao-yao/ipu6-drivers/commit/4714875d81a69705650f8aa859ab46af508b9ae1 to fix the test build ?

**Comment by hao-yao** [comment]
> If software_node_register_node_group() is available in all the kernel versions you want to support then yes that should work.

Seems software_node_register_nodes() is available between v5.3 ~ v6.2, software_node_register_node_group() since v5.8 and ipu3-cio2 since v5.12. So I thinks it is safe to directly use software_node_register_node_group().

> Shall I push a new version cherry-picking the upstream fix + adding [hao-yao@4714875](https://github.com/hao-yao/ipu6-drivers/commit/4714875d81a69705650f8aa859ab46af508b9ae1) to fix the test build ?

Yes, please add the commit to fix test build. For the upstream fix in ipu3-cio2, please focus only on kernel API changes. Thanks!

**Comment by hao-yao** [comment]
How about this? @jwrdegoede 

```diff
diff --git a/drivers/media/pci/intel/cio2-bridge.c b/drivers/media/pci/intel/cio2-bridge.c
index fe7175ddd..93bac8c4e 100644
--- a/drivers/media/pci/intel/cio2-bridge.c
+++ b/drivers/media/pci/intel/cio2-bridge.c
@@ -221,6 +221,20 @@ static void cio2_bridge_init_swnode_names(struct cio2_sensor *sensor)
                 SWNODE_GRAPH_ENDPOINT_NAME_FMT, 0); /* And endpoint 0 */
 }
 
+static void cio2_bridge_init_swnode_group(struct cio2_sensor *sensor)
+{
+       struct software_node *nodes = sensor->swnodes;
+
+       sensor->group[SWNODE_SENSOR_HID] = &nodes[SWNODE_SENSOR_HID];
+       sensor->group[SWNODE_SENSOR_PORT] = &nodes[SWNODE_SENSOR_PORT];
+       sensor->group[SWNODE_SENSOR_ENDPOINT] = &nodes[SWNODE_SENSOR_ENDPOINT];
+       sensor->group[SWNODE_CIO2_PORT] = &nodes[SWNODE_CIO2_PORT];
+       sensor->group[SWNODE_CIO2_ENDPOINT] = &nodes[SWNODE_CIO2_ENDPOINT];
+       if (sensor->ssdb.vcmtype &&
+           sensor->ssdb.vcmtype <= ARRAY_SIZE(cio2_vcm_types))
+               sensor->group[SWNODE_VCM] = &nodes[SWNODE_VCM];
+}
+
 static void cio2_bridge_create_connection_swnodes(struct cio2_bridge *bridge,
                                                  struct cio2_sensor *sensor)
 {
@@ -254,6 +268,8 @@ static void cio2_bridge_create_connection_swnodes(struct cio2_bridge *bridge,
                         sensor->ssdb.link);
                nodes[SWNODE_VCM] = NODE_VCM(vcm_node_name);
        }
+
+       cio2_bridge_init_swnode_group(sensor);
 }
 
 static void cio2_bridge_instantiate_vcm_i2c_client(struct cio2_sensor *sensor)
@@ -293,7 +309,7 @@ static void cio2_bridge_unregister_sensors(struct cio2_bridge *bridge)
 
        for (i = 0; i < bridge->n_sensors; i++) {
                sensor = &bridge->sensors[i];
-               software_node_unregister_nodes(sensor->swnodes);
+               software_node_unregister_node_group(sensor->group);
                ACPI_FREE(sensor->pld);
                acpi_dev_put(sensor->adev);
                i2c_unregister_device(sensor->vcm_i2c_client);
@@ -352,7 +368,7 @@ static int cio2_bridge_connect_sensor(const struct cio2_sensor_config *cfg,
                cio2_bridge_create_fwnode_properties(sensor, bridge, cfg);
                cio2_bridge_create_connection_swnodes(bridge, sensor);
 
-               ret = software_node_register_nodes(sensor->swnodes);
+               ret = software_node_register_node_group(sensor->group);
                if (ret)
                        goto err_free_pld;
 
@@ -379,7 +395,7 @@ static int cio2_bridge_connect_sensor(const struct cio2_sensor_config *cfg,
        return 0;
 
 err_free_swnodes:
-       software_node_unregister_nodes(sensor->swnodes);
+       software_node_unregister_node_group(sensor->group);
 err_free_pld:
        ACPI_FREE(sensor->pld);
 err_put_adev:
diff --git a/drivers/media/pci/intel/cio2-bridge.h b/drivers/media/pci/intel/cio2-bridge.h
index a0c99ba8f..3f9080273 100644
--- a/drivers/media/pci/intel/cio2-bridge.h
+++ b/drivers/media/pci/intel/cio2-bridge.h
@@ -119,8 +119,9 @@ struct cio2_sensor {
        struct acpi_device *adev;
        struct i2c_client *vcm_i2c_client;
 
-       /* SWNODE_COUNT + 1 for terminating empty node */
-       struct software_node swnodes[SWNODE_COUNT + 1];
+       /* SWNODE_COUNT + 1 for terminating NULL */
+       const struct software_node *group[SWNODE_COUNT + 1];
+       struct software_node swnodes[SWNODE_COUNT];
        struct cio2_node_names node_names;
 
        struct cio2_sensor_ssdb ssdb;
```

**Comment by jwrdegoede** [comment]
> How about this? @jwrdegoede

Ack that looks good to me.

**Comment by jwrdegoede** [comment]
Ok, I've just pushed a new version with:
1. Your ubuntu-23.04 fix added
2. The upstream change fixing the build cherry-picked, with the VCM check extended with an extra `sensor->ssdb.vcmtype <= ARRAY_SIZE(cio2_vcm_types)` check.

**Comment by bjesus** [comment]
@jwrdegoede thank you for all your work 🙏 I can confirm I can finally use the camera on an unpatched 6.3 kernel :)

**Pull request merged**
